export const SELECT_PRESSURE = "SELECT_PRESSURE";
export const SELECT_HUMIDITY = "SELECT_HUMIDITY";
export const SELECT_TEMP_HOME = "SELECT_TEMP_HOME";
export const SELECT_TEMP_WORK = "SELECT_TEMP_WORK";
export const SELECT_LEVEL = "SELECT_LEVEL";
export const SELECT_MASS = "SELECT_MASS";
export const SELECT_WATER = "SELECT_WATER";
export const SELECT_CO2 = "SELECT_CO2";
export const SELECT_JOURNAL = "SELECT_JOURNAL";

export const SELECT_MENU_ITEM = "SELECT_MENU_ITEM";
